In [1]:
print('hello')

hello


In [2]:
from epidatpy import EpiDataContext, EpiRange

# Create the client object.
epidata = EpiDataContext()
apicall = epidata.pub_covidcast(
    data_source="jhu-csse",
    signals="confirmed_cumulative_num",
    geo_type="nation",
    time_type="day",
    geo_values="us",
    time_values=EpiRange(20210405, 20210410),
)
print(apicall.df())

d:\API Developement\multi_agents_health_wellness_app\.venv\Lib\site-packages\epidatpy\_auth.py:9: UserWarning: DELPHI_EPIDATA_KEY environment variable not set. Please set it to your Epidata API key to avoid rate limits. You can get a free key at: https://api.delphi.cmu.edu/epidata/admin/registration_form
  warnings.warn(


     source                    signal geo_type geo_value time_type time_value  \
0  jhu-csse  confirmed_cumulative_num   nation        us       day 2021-04-05   
1  jhu-csse  confirmed_cumulative_num   nation        us       day 2021-04-06   
2  jhu-csse  confirmed_cumulative_num   nation        us       day 2021-04-07   
3  jhu-csse  confirmed_cumulative_num   nation        us       day 2021-04-08   
4  jhu-csse  confirmed_cumulative_num   nation        us       day 2021-04-09   
5  jhu-csse  confirmed_cumulative_num   nation        us       day 2021-04-10   

       issue  lag       value  stderr  sample_size  direction  missing_value  \
0 2023-03-10  704  30874278.0    <NA>         <NA>       <NA>              0   
1 2023-03-10  703  30937664.0    <NA>         <NA>       <NA>              0   
2 2023-03-10  702  31013399.0    <NA>         <NA>       <NA>              0   
3 2023-03-10  701  31093208.0    <NA>         <NA>       <NA>              0   
4 2023-03-10  700  31177602.0   

In [4]:
apicall

EpiDataCall(endpoint=covidcast/, params={'data_source': 'jhu-csse', 'signals': 'confirmed_cumulative_num', 'geo_type': 'nation', 'time_type': 'day', 'geo_values': 'us', 'time_values': '20210405-20210410'})

EpiDataCall(endpoint=covidcast/, params={'data_source': 'jhu-csse', 'signals': 'confirmed_cumulative_num', 'geo_type': 'nation', 'time_type': 'day', 'geo_values': 'us', 'time_values': '20210405-20210410'})


In [23]:
apicall.df

<bound method EpiDataCall.df of EpiDataCall(endpoint=covidcast/, params={'data_source': 'jhu-csse', 'signals': 'confirmed_cumulative_num', 'geo_type': 'nation', 'time_type': 'day', 'geo_values': 'us', 'time_values': '20210405-20210410'})>

<bound method EpiDataCall.df of EpiDataCall(endpoint=covidcast/, params={'data_source': 'jhu-csse', 'signals': 'confirmed_cumulative_num', 'geo_type': 'nation', 'time_type': 'day', 'geo_values': 'us', 'time_values': '20210405-20210410'})>

In [6]:
import requests
from typing import Dict

In [11]:
import requests
from langchain.tools import tool

@tool
def get_drug_label_info(ingredient: str) -> dict:
    """
    Fetches drug label information for a given active ingredient from the OpenFDA Drug Label API.

    Args:
        ingredient (str): The active drug ingredient to search for (e.g., 'paracetamol').

    Returns:
        dict: A dictionary containing drug label data such as active ingredient, purpose, warnings, dosage, etc.
            Metadata like disclaimer and terms are excluded.
            Returns an empty dict if no results are found or the API fails.
    """
    try:
        url = f"https://api.fda.gov/drug/label.json?search=active_ingredient:%22{ingredient}%22&limit=1"
        response = requests.get(url, timeout=10)
        response.raise_for_status()
        data = response.json()
        
        # Return only the first result if available
        if "results" in data and len(data["results"]) > 0:
            return data["results"][0]
        else:
            return {}
        
    except Exception as e:
        return {"error": str(e)}

In [12]:
get_drug_label_info.description

"Fetches drug label information for a given active ingredient from the OpenFDA Drug Label API.\n\nArgs:\n    ingredient (str): The active drug ingredient to search for (e.g., 'paracetamol').\n\nReturns:\n    dict: A dictionary containing drug label data such as active ingredient, purpose, warnings, dosage, etc.\n        Metadata like disclaimer and terms are excluded.\n        Returns an empty dict if no results are found or the API fails."

In [13]:
response = get_drug_label_info.invoke(
    {
        'ingredient': 'paracetamol'
    }
)

In [14]:
response

{'spl_product_data_elements': ['L-Oral PARACETAMOL Syrup Paracetamol METHYLPARABEN PROPYLPARABEN POTASSIUM SORBATE CITRIC ACID MONOHYDRATE SORBITOL PROPYLENE GLYCOL SUCRALOSE POVIDONE K30 GLYCERIN FD&C RED NO. 40 D&C RED NO. 33 WATER ACETAMINOPHEN ACETAMINOPHEN'],
 'spl_unclassified_section': ['DRUG FACTS',
  '√ Fever reducer - Pain reliever √ Alcohol Free √ Aspirin Free Manufactured by : Global Pharma Healthcare Pvt. Ltd., A-9, SIDCO Pharmaceutical Complex, Alathur-603 110 - INDIA. www.global-pharma.com'],
 'active_ingredient': ['Active ingredient Paracetamol 160 mg'],
 'purpose': ['Purpose Pain reliever - Fever reducer'],
 'inactive_ingredient': ['INACTIVE INGREDIENTS Artificial flavour, Methylparaben, Propylparaben, Potassium sorbate, Citric Acid Monohydrate, Sorbitol, Propylene glycol, Sucralose, Povidone K30, Glycerin, FD&C Red #40, D&C Red #33 & Purified water.'],
 'indications_and_usage': ['USES Temporarily relieves minor aches and pains due to: • The common cold • Flu • Headach

In [17]:
response = get_drug_label_info.invoke(
    {
        'ingredient': 'cetirizine'
    }
)

In [18]:
response

{'spl_product_data_elements': ['Allergy Relief Cetirizine HCl 10 mg CETIRIZINE HYDROCHLORIDE CETIRIZINE HYPROMELLOSES LACTOSE MONOHYDRATE MAGNESIUM STEARATE CELLULOSE, MICROCRYSTALLINE POLYETHYLENE GLYCOL, UNSPECIFIED TITANIUM DIOXIDE SILICON DIOXIDE CROSCARMELLOSE SODIUM G;4 pillow-shaped'],
 'active_ingredient': ['Active ingredient Cetirizine HCl 10 mg'],
 'purpose': ['Purpose Antihistamine'],
 'indications_and_usage': ['Uses temporarily relieves these symptoms due to hay fever or other upper respiratory allergies: runny nose sneezing itchy, watery eyes itching of the nose or throat'],
 'warnings': ['Warnings Do not use if you have ever had an allergic reaction to this product or any of its ingredients, or to an antihistamine containing hydroxyzine Ask a doctor before use if you have liver or kidney disease. Your doctor should determine if you need a different dose. Ask doctor or pharmacist before use if you are taking sedatives or tranquilizers When using this product drowsiness may

In [20]:
import requests
from dotenv import load_dotenv
import os

load_dotenv()

API_KEY = os.getenv("AIR_QUALITY_API_KEY")
url = "https://www.airnowapi.org/aq/observation/zipCode/current/"

params = {
    "format": "application/json",
    "zipCode": "90210",
    "distance": 25,
    "API_KEY": API_KEY
}

try:
    response = requests.get(url, params=params, timeout=10)
    response.raise_for_status()
    data = response.json()
    print("✅ API Response:")
    print(data)

except requests.exceptions.HTTPError as errh:
    print("❌ HTTP Error:", errh)
except requests.exceptions.ConnectionError as errc:
    print("❌ Connection Error:", errc)
except requests.exceptions.Timeout as errt:
    print("❌ Timeout Error:", errt)
except requests.exceptions.RequestException as err:
    print("❌ Request Exception:", err)


✅ API Response:
[{'DateObserved': '2025-07-29', 'HourObserved': 4, 'LocalTimeZone': 'PST', 'ReportingArea': 'NW Coastal LA', 'StateCode': 'CA', 'Latitude': 34.0505, 'Longitude': -118.4566, 'ParameterName': 'O3', 'AQI': 10, 'Category': {'Number': 1, 'Name': 'Good'}}]


[{'DateObserved': '2025-07-29', 'HourObserved': 4, 'LocalTimeZone': 'PST', 'ReportingArea': 'NW Coastal LA', 'StateCode': 'CA', 'Latitude': 34.0505, 'Longitude': -118.4566, 'ParameterName': 'O3', 'AQI': 10, 'Category': {'Number': 1, 'Name': 'Good'}}]

In [21]:
import requests
from langchain.tools import tool
from dotenv import load_dotenv
import os

load_dotenv()

@tool
def get_air_quality_by_zip(zip_code: str) -> dict:
    """
    Fetches current air quality index (AQI) information for a given U.S. ZIP code 
    using the AirNow API.

    Args:
        zip_code (str): A 5-digit U.S. ZIP code (e.g., '90210').

    Returns:
        dict: A dictionary with observed date, area, AQI value, pollutant name, and category.
            Returns an error message if data is unavailable or the request fails.
    """
    API_KEY = os.getenv("AIR_QUALITY_API_KEY") 
    url = "https://www.airnowapi.org/aq/observation/zipCode/current/"

    params = {
        "format": "application/json",
        "zipCode": zip_code,
        "distance": 25,
        "API_KEY": API_KEY
    }

    try:
        response = requests.get(url, params=params, timeout=10)
        response.raise_for_status()
        data = response.json()

        if not data:
            return {"message": f"No air quality data found for ZIP code {zip_code}."}

        # Return first pollutant's data
        pollutant = data[0]
        return {
            "area": pollutant["ReportingArea"],
            "state": pollutant["StateCode"],
            "latitude": pollutant["Latitude"],
            "longitude": pollutant["Longitude"],
            "pollutant": pollutant["ParameterName"],
            "aqi": pollutant["AQI"],
            "category": pollutant["Category"]["Name"],
            "observed_date": pollutant["DateObserved"],
            "observed_hour": pollutant["HourObserved"],
            "timezone": pollutant["LocalTimeZone"]
        }

    except Exception as e:
        return {"error": str(e)}


In [22]:
result = get_air_quality_by_zip.invoke({'zip_code': '90210'})
print(result)

{'area': 'NW Coastal LA', 'state': 'CA', 'latitude': 34.0505, 'longitude': -118.4566, 'pollutant': 'O3', 'aqi': 10, 'category': 'Good', 'observed_date': '2025-07-29', 'observed_hour': 4, 'timezone': 'PST'}


{'area': 'NW Coastal LA', 'state': 'CA', 'latitude': 34.0505, 'longitude': -118.4566, 'pollutant': 'O3', 'aqi': 10, 'category': 'Good', 'observed_date': '2025-07-29', 'observed_hour': 4, 'timezone': 'PST'}